### ISSUE TITLE
Story Promo 'top' variant sizing bug at 1280px exactly

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#3124] opened 2020-02-13 08:23 UTC
**Describe the bug**
A Story Promo 'top' variant has a bug where when the page is exactly 1280px, the image spans 3 grid columns and not 6, so leaves 3 columns of space. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.bbc.com/pidgin
2. Resize browser window to exactly 1280px.
3. See error

**Expected behaviour**
The image should span all 6 columns. 

**Screenshots**

**Desktop (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
This is likely a bug with the media query being set at the incorrect min/max values so that's why it works for <=1279px and >=1281px.

**Comment by DenisHdz** [comment] 2020-02-13 10:05
The issue is due to `GEL_GROUP_4_SCREEN_WIDTH_MAX` being set to `80rem` when it should be `79.9375` (`1279/16`). Will open a PR to fix this in `psammead-gel-foundations`.

**Comment by DenisHdz** [comment] 2020-02-13 12:25
This has now been fixed in https://github.com/bbc/psammead/pull/3129/files

**Closed as completed by DenisHdz** 2020-02-13 12:25 UTC
Labels: ws-home, ws-front-page-layout
