### ISSUE TITLE
Validate components when bumping

### ISSUE THREAD

**Issue by ChrisBAshton** [BBC-archive/psammead#146] opened 2018-12-07 11:43 UTC
**Is your feature request related to a problem? Please describe.**
We should have an automated checker that ensures that components are correctly versioned when we apply updates to them.

* NPM package version should have been increased
* package-lock.json should have been increased and should match that of the package.json
* Changelog.md should have a new entry describing what is being changed.

**Describe the solution you'd like**
A script that validates these things, and that runs on the PR and offers a status check. It should have a red cross when the component doesn't validate, to prevent merge.

**Describe alternatives you've considered**
Continuing as we are, which is to check these things manually.

**Testing notes**
[Tester to complete]

Dev insight: ideally a validation script should have unit tests which makes sure it works as expected. For manually testing, you should be able to make a change to any file in a package, open a PR, and see the automated checklist fail because you haven't bumped things as expected.

**Additional context**
Original issue in #64.

**Comment by rossgaskell** [comment] 2019-06-04 10:20
Closing as duplicate of #131 

> Some of these checks can be mitigated by the use of a package generator, e.g. generating the ideal package.json, a readme and change log etc.
> 
> Automatically checking to see if a package has been bumped is more difficult and not really useful to us as you do not always have to bump a package version when making changes

**Closed as completed by rossgaskell** 2019-06-04 10:20 UTC
Labels: simorgh-core-stream
