### ISSUE TITLE
Input provider is broken

### ISSUE THREAD

**Issue by dr3** [BBC-archive/psammead#2346] opened 2019-10-07 16:26 UTC
**Describe the bug**
In psammead multiple stories use the input provider package, but all of them appear broken. They should allow you to manually edit text, but now it only lets you select the service

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://bbc.github.io/psammead/?path=/story/components-headline--default
2. See lack of ability to adjust text despite it being desired https://github.com/bbc/psammead/blob/latest/packages/components/psammead-headings/src/index.stories.jsx#L13

**Expected behaviour**
It works as expected

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment] 2019-10-07 20:17
Closing as this is not a bug, the functionality was removed as apart of https://github.com/bbc/psammead/issues/1598

**Closed as completed by chris-hinds** 2019-10-07 20:17 UTC
Labels: bug, simorgh-core-stream
