### ISSUE TITLE
Resolve Safari icon positioning bug in Psammead Promo

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#3486] opened 2020-05-20 14:36 UTC
### Is your feature request related to a problem? Please describe.
In Safari the content-type icon (e.g. Camera for photo galleries) bleeds out of its container. See screenshot. Confirmation from Media team as this also affects the related content block.

### Describe the solution you'd like
Ensure icon is positioned within the confines of the promo image. 

### Describe alternatives you've considered
n/a

### Testing notes
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
![image](https://user-images.githubusercontent.com/1430787/82565080-b647f400-9b71-11ea-9363-adebd72cbb01.png)

**What it should look like:**
<img width="482" alt="Screenshot 2020-06-05 at 12 12 36" src="https://user-images.githubusercontent.com/4706195/83870297-eb357880-a725-11ea-86b9-e18ffe2f45d0.png">

**Comment by FK78** [comment] 2020-06-09 15:39
The issue is only present on Safari using an iPhone.

I've been able to replicate the issue using Mac Safari by using https://developer.apple.com/safari/tools/ (kudos to @thekp).

**Comment by aeroplanejane** [comment] 2021-04-20 12:53
Closing as won't do.

**Closed as completed by aeroplanejane** 2021-04-20 12:53 UTC
Labels: good first issue, low-priority, ux
