### ISSUE TITLE
Simplify psammead-media-player

### ISSUE THREAD

**Issue by simonsinclair** [BBC-archive/psammead#2544] opened 2019-11-04 12:23 UTC
**Is your feature request related to a problem? Please describe.**
The successful integration of Media Player into various areas of Simorgh, plus additional features like Play Button and Guidance has meant a vast increase in its complexity over the past couple of weeks.

It contains three major components - Placeholder, CanonicalMediaPlayer and AmpMediaPlayer - and has upwards of 15 properties, with more expected. We'd like to determine whether this component can be simplified and what this would look like.

**Describe the solution you'd like**

- Does grouping props (like `mediaInfo`) help us or not?
- Should Placeholder be a dependency of Media Player or not?
  - Placeholder itself is a growing component, with additional features requiring new properties.
- Should Guidance be a more generic Overlay component?

**Describe alternatives you've considered**
n/a

**Testing notes**
[Tester to complete]

Dev insight: Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment] 2019-11-22 14:38
Hey @simonsinclair is this ticket a duplicate of https://github.com/bbc/simorgh/issues/4361? Can it be closed?

**Comment by simonsinclair** [comment] 2019-11-22 16:30
> Hey @simonsinclair is this ticket a duplicate of [bbc/simorgh#4361](https://github.com/bbc/simorgh/issues/4361)? Can it be closed?

Hey @aeroplanejane, this issue relates to Psammead Media Player and _not_ the `news-av-player` Morph module. 🙂

**Closed as completed** 2021-07-29 16:07 UTC
Labels: Refinement Needed, articles-av-epic, backlog
