### ISSUE TITLE
Most Read: Wrong font size for headline at mobile width

### ISSUE THREAD

**Issue by thekp** [BBC-archive/psammead#3122] opened 2020-02-12 14:37 UTC
**Describe the bug**
Following a manual test on this PR: https://github.com/bbc/simorgh/pull/5437, it was spotted that the wrong font-size is being used for our item headlines for all services. The font-size is currently 18px, however it should be 16px

These are our most-read font-size requirements:
```
Most read, title
Double Pica
Mobile up to 599px, 20 font size /24 line height
Desktop from 600px, 24/28
Most Read Headline text
Pica
Mobile up to 399px, 16/20
Great Primer
Desktop from 400px, 20/24
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://bbc.github.io/simorgh/?path=/story/containers-mostread--canonical-most-read'
2. Inspect and adjust to a mobile viewport
3. Inspect an item headline element

**Expected behaviour**
Font-size should be 16px for mobile viewport

**Screenshots**
![image](https://user-images.githubusercontent.com/30599794/74344853-1e35b400-4da5-11ea-8cf2-4d2d32b064ff.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by hotinglok** [comment] 2020-02-17 12:07
Checked in with Natalie from UX, the 18px comes from Great Primer between 400px - 600px. Since the requirements are that it is only in Pica up to 400px, this is fine and expected behaviour for now. Will reopen if this is to be changed after the final UX review of MostRead.

**Closed as completed by hotinglok** 2020-02-17 12:07 UTC
Labels: bug, ws-home, most-read
